/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipc;

import java.io.Console;
import javax.swing.JOptionPane;

/**
 *
 * @author jeanp
 */
public class MemoryConfig extends javax.swing.JFrame {
    
    MiniPC miPc;
    /**
     * Creates new form MemoryConfig
     */
    public MemoryConfig(MiniPC miPc) {
        initComponents();
        this.miPc = miPc;
        inputTamMemoria.setText(Integer.toString(miPc.getTamMemoria()));
        inputTamMemOS.setText(Integer.toString(miPc.getTamMemoriaOS()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        inputTamMemoria = new javax.swing.JTextField();
        inputTamMemOS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jProgressBar1.setValue(20);

        inputTamMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTamMemoriaActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(inputTamMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(71, 71, 71)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputTamMemOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(inputTamMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(inputTamMemOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTamMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTamMemoriaActionPerformed
        // TODO add your handling code here:
        if (inputTamMemoria.getText().isEmpty()) {
            System.out.println("No se ha ingresado un valor");
            return;
        }
        if (!Verifier.esEntero(inputTamMemoria.getText())) {
            System.out.println("El valor ingresado no es un entero");
            return;
        }
        String tamanioMemoria = inputTamMemoria.getText();
        if(Integer.parseInt(tamanioMemoria) >= 50){
            System.out.println(tamanioMemoria);
            jProgressBar1.setMaximum(Integer.parseInt(tamanioMemoria));
            inputTamMemOS.setText(Integer.toString(miPc.getTamMemoriaOS()));
        }
        else{
            System.out.println("La memoria no puede ser menor a 50");
        }
        
    }//GEN-LAST:event_inputTamMemoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mensajeError = "";
        if (inputTamMemoria.getText().isEmpty() || inputTamMemOS.getText().isEmpty()) {
            System.out.println("No se han ingresado valores");
            mensajeError = "No se han ingresado valores";

        }
        if (Integer.parseInt(inputTamMemOS.getText()) >= Integer.parseInt(inputTamMemoria.getText())) {
            System.out.println("El tamaño de la memoria del sistema operativo no puede ser mayor o igual al de la memoria");
            mensajeError = "El tamaño de la memoria del sistema operativo no puede ser mayor o igual al de la memoria";

        }
        if (!Verifier.esEntero(inputTamMemoria.getText()) || !Verifier.esEntero(inputTamMemOS.getText())) {
            System.out.println("Los valores ingresados no son enteros");
            mensajeError = "Los valores ingresados no son enteros";

        }
        if (Integer.parseInt(inputTamMemOS.getText()) < 20) {
            System.out.println("El tamaño de la memoria del sistema operativo no puede ser menor a 20");
            mensajeError = "El tamaño de la memoria del sistema operativo no puede ser menor a 20";
            inputTamMemOS.setText("20");


            
        }
        if (Integer.parseInt(inputTamMemoria.getText()) < 50) {
            System.out.println("El tamaño de la memoria no puede ser menor a 50");
            mensajeError = "El tamaño de la memoria no puede ser menor a 50";
            inputTamMemoria.setText("50");

        }
        
        if (!mensajeError.isEmpty()) {
            JOptionPane.showMessageDialog(null, mensajeError);
            return;
        }else{
            miPc.setTamMemoria(Integer.parseInt(inputTamMemoria.getText()));
            miPc.setTamMemoriaOS(Integer.parseInt(inputTamMemOS.getText()));
            this.dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputTamMemOSActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        if (inputTamMemOS.getText().isEmpty()) {
            System.out.println("No se ha ingresado un valor");
            return;
        }
        if (!Verifier.esEntero(inputTamMemOS.getText())) {
            System.out.println("El valor ingresado no es un entero");
            return;
        }
        String tamanioMemoria = inputTamMemOS.getText();
        if(Integer.parseInt(tamanioMemoria) <= 20){
            System.out.println("El tamaño de la memoria del sistema operativo no puede ser menor a 20");
        }
        else{
            if (Integer.parseInt(tamanioMemoria) == Integer.parseInt(inputTamMemoria.getText())) {
                System.out.println("El tamaño de la memoria del sistema operativo no puede ser igual al de la memoria");
            }
            else{
                jProgressBar1.setValue(Integer.parseInt(tamanioMemoria));
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoryConfig(new MiniPC()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputTamMemOS;
    private javax.swing.JTextField inputTamMemoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
